# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure

      # - name: Run tests
      #   run: |
      #     poetry run pytest --cov=src --cov-report=term

      - name: Run mypy
        run: |
          poetry run mypy src/ --config-file=mypy.ini

      - name: Run ruff
        run: |
          poetry run ruff check src/
